name: Node.js CI
on: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
        
    - run: npm run build --if-present
    - run: npm test
