name: Node.js CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
